// Every way a king ends. `stat` deaths are triggered by a meter reaching 0
// (`low`) or 100 (`high`). The others are triggered by cards via `die`.
export const DEATHS = {
  // meter deaths
  faith_low: { title: "Burned as a Heretic", text: "The Flame went out in the temples and the Flamekeepers decided that was your fault. They relit it with you.", glyph: "†" },
  faith_high: { title: "Made a Saint", text: "The Church declared you holy. Holy men belong to the Flame, not the throne. They took you apart for relics while you were still explaining.", glyph: "▲" },
  people_low: { title: "Rats", text: "The city emptied. Those who stayed were not people anymore, exactly. Nobody found the body. Something did.", glyph: "☠" },
  people_high: { title: "Loved to Death", text: "They adored you. They carried you through the streets on their shoulders, then over the bridge, then over the rail. They were still cheering.", glyph: "♥" },
  army_low: { title: "An Empty Gate", text: "There was no one left to hold the gate. Whoever came through it did not introduce themselves.", glyph: "▮" },
  army_high: { title: "Hanged by the Marshal", text: "The army had grown big enough to notice it didn't need you. Marshal Thorne apologised. He'd always liked you.", glyph: "⚔" },
  gold_low: { title: "Debtor's Grave", text: "The Deep Holds foreclosed on the palace. Clause nine covered the king. It was a very thorough contract.", glyph: "◈" },
  gold_high: { title: "Choked at the Feast", text: "So much gold demanded a feast. The feast demanded a pie. The pie demanded a whole swan. You did not chew.", glyph: "¤" },

  // card deaths
  duel: { title: "A Fair Fight", text: "It was fair. That was the problem.", glyph: "⚔" },
  poison: { title: "Something in the Wine", text: "You noticed the taste. You noticed it too late, with interest.", glyph: "⚗" },
  assassin_blade: { title: "Quiet Hands", text: "The Guild always finishes a contract. They left a receipt.", glyph: "◌" },
  fell_from_tower: { title: "A Long Way Down", text: "The view from the tower was excellent for nearly four seconds.", glyph: "▼" },
  eaten_by_dragon: { title: "Eaten", text: "Vorrath said he would. Vorrath keeps his word.", glyph: "◆" },
  drowned: { title: "Drowned", text: "Kings do not float better than anyone else. This surprised you.", glyph: "≋" },
  burned_as_heretic: { title: "Burned", text: "The Flamekeepers said it would purify you. You are, technically, very clean.", glyph: "†" },
  hanged_by_army: { title: "Hanged", text: "The army voted. You were not consulted.", glyph: "⚔" },
  torn_by_mob: { title: "Torn Apart", text: "The people wanted a piece of you. Each of them.", glyph: "☠" },
  choked_at_feast: { title: "Choked", text: "It was a very good pie.", glyph: "¤" },
  plague: { title: "The Grey Cough", text: "The cough came for the cooper, the tanner, the baker, and then it came upstairs.", glyph: "☠" },
  old_age: { title: "Old Age", text: "You died in bed, which your ancestors would have considered showing off.", glyph: "⌛" },
  dungeon: { title: "Lost Below", text: "The Deep does not return what it is given. It counted you as given.", glyph: "▽" },
  broken_heart: { title: "A Broken Heart", text: "The physician wrote 'heart' on the certificate and could not, with a straight face, write anything else.", glyph: "♥" },
  stepped_on_by_giant: { title: "Underfoot", text: "Ombrun was very sorry. He said so, from quite high up.", glyph: "▮" },
  cursed: { title: "The Bargain Came Due", text: "He had told you the price. You had agreed. He is, above everything, fair.", glyph: "✦" },
  frozen: { title: "Frozen", text: "The Iron Teeth in winter do not care whose crown it is.", glyph: "❄" },
  avalanche: { title: "Avalanche", text: "The dwarves had warned you not to shout in the pass. You had felt the need to make a point.", glyph: "▲" },
  struck_by_lightning: { title: "Struck", text: "You had just said 'what are the odds'.", glyph: "↯" },
  bad_mushroom: { title: "The Wrong Mushroom", text: "Old Mab said the blue ones. These were, in fairness, bluish.", glyph: "☂" },
  orc_axe: { title: "An Axe, Honestly Delivered", text: "Grukhar looked you in the eye first. Among the Ashfang this counts as a kindness.", glyph: "⚔" },
  elf_arrow: { title: "One Arrow", text: "The elves only needed one. They had, they mentioned later, been aiming for eleven hundred years.", glyph: "➶" },
  dwarven_contract: { title: "Foreclosed", text: "You were collateral. It was in the schedule of annexes. You should have read the annexes.", glyph: "◈" },
  troll_toll: { title: "Toll Unpaid", text: "The troll was very clear about the toll. You were very clear about not paying it. Only one of you was a troll.", glyph: "▮" },
  fae_bargain: { title: "Taken by the Fair Folk", text: "You had said 'I'd give anything'. They took it very seriously, and then they took you.", glyph: "✧" },
  lost_at_sea: { title: "Lost at Sea", text: "Captain Sable sent your crown back. Just the crown.", glyph: "≋" },
  wolves: { title: "Wolves", text: "The Thornwood is theirs at night. It was night.", glyph: "☾" },
  explosion: { title: "Alchemical Accident", text: "Master Quill said it was perfectly safe. Master Quill said it from behind a wall.", glyph: "✸" },
  vampire: { title: "A Long Dinner", text: "Count Vesper was a gracious host. You were a gracious meal.", glyph: "♆" },
  buried_alive: { title: "Buried", text: "The stone was very old and very heavy and did not know you were still breathing.", glyph: "▽" },
  peaceful: { title: "Walked Away", text: "You left the crown on the chair and went to see about some goats. No one stopped you. That stung a little.", glyph: "❀" },
};
